### ISSUE TITLE
Scrap hl7 standards for automation and self-updating

### ISSUE THREAD

**Issue by LaRiffle** [arkhn/fhir-store#2]
# Scrap hl7 standards to keep updated

The [hl7 reference](https://www.hl7.org/fhir/resourcelist.html) (See **R2 Layout** tab) is a complex and exhaustive description of the resources needed, which evolves in time. Once we have replicated this structure in our repo, we need to keep up to date automatically. Hence, scrapping is very good option to make the first building of the structure and to apply all the updates as they arrive.

We have experienced issues with scrapping this website (issues with certificates I think), but succeeding in this scrapping task would be very valuable for the community. Anyone with a bit of experience in scrapping is very much welcome!

Once this milestone is reached, the second step is to scrap the content of each Resource. Each has a link (See for example [Patient](https://www.hl7.org/fhir/patient.html) in the **Json tab**) where you can find a JSON-like description. _We already have a parser for this kind of data to convert it in our yml format and conventions_, so the scrapping part is particularly crucial to have the whole pipeline!

**Comment by kir0ul** [comment]
Same problem here:
```
DEBUG: Retrying <GET https://www.hl7.org/fhir/resourcelist.html> (failed 1 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost:
 Connection to the other side was lost in a non-clean fashion: Connection lost.>]
```
Same problem with `cURL`:
```
curl -v https://www.hl7.org/fhir/resourcelist.html     
*   Trying 64.9.200.35...
* TCP_NODELAY set
* Connected to www.hl7.org (64.9.200.35) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* Unknown SSL protocol error in connection to www.hl7.org:443
* Curl_http_done: called premature == 1
* stopped the pause stream!
* Closing connection 0
curl: (35) Unknown SSL protocol error in connection to www.hl7.org:443
```
But replacing HTTPS by HTTP works just fine! ;)

**Comment by kir0ul** [comment]
I think I got it working to scrap all the JSON snippets. But I guess it still needs some post-process on the JSON markup. I quickly tried the `html2text` module, but the cleaning is not enough to get a correct JSON file. Some more work is needed on that part.

**Comment by LaRiffle** [comment]
Ok good I'll look at it! 
We already know how to clean the "dirty" json like the one here, extracted manually: https://github.com/arkhn/fhir-store/blob/master/patient.json, so this part is not a problem. :)

**Comment by kir0ul** [comment]
ToDo:
- Check right number of links
- Better clean JSON file (see `Patient.json`)
- Get the tree to create the right directories

**Comment by kir0ul** [comment]
@LaRiffle It should be ok to review the PR now.
To review it you should be in the `scrap` folder and run `scrapy crawl hl7`. Since some more lines of code are needed to run Scrapy from a script and not from the command line, I plan to add the tests in https://github.com/arkhn/fhir-store/issues/8
